language: python
python:
  - "2.6"
  - "2.7"
  # 3.2 make unicode literal handling difficult. 
  # we dropped that, see https://github.com/rthalley/dnspython/pull/148
  # for comments
  #- "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
 - pip install unittest2 pylint
script:
 - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then make lint; fi
 - make test
